import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
// HYPERREAL API INTEGRATION - Removed @google/generative-ai import
import session from 'express-session';
import RedisStore from 'connect-redis';
import { createClient } from 'redis';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();

app.set('trust proxy', 1);

// Redis client for session storage
const redisClient = createClient({
    url: process.env.REDIS_URL
});

// Connect to Redis
console.log("Attempting Redis connection...");
try {
    await redisClient.connect();
    console.log('✅ Redis connected successfully');
} catch (error) {
    console.error('❌ Redis connection failed:', error.message);
    console.log("Continuing without Redis session storage");
}

// Redis store for sessions
let redisStore;

if (redisClient.isReady) {
    redisStore = new RedisStore({
        client: redisClient,
        prefix: "sess:"
    });
}

// Validate session secret
const sessionSecret = process.env.SESSION_SECRET;
if (!sessionSecret) {
    console.error('❌ FATAL ERROR: SESSION_SECRET environment variable is missing.');
    process.exit(1);
}

// Session middleware
app.use(session({
    store: redisClient.isReady ? redisStore : undefined,
    secret: sessionSecret,
    resave: false,
    saveUninitialized: true, // IMPORTANT: Needed to generate req.session.id for new users!
    cookie: {
        secure: process.env.NODE_ENV === 'production',
        httpOnly: true,
        maxAge: 24 * 60 * 60 * 1000 // 24 hours
    }
}));

// Rate limiting
const limiter = rateLimit({
    windowMs: 15 * 60 * 1000, // 15 minutes
    max: 50, // Stricter limit: 50 requests per 15 minutes
    message: { reply: 'Too many requests, please try again later.' },
    keyGenerator: (req) => {
        // Limit by session ID if available, otherwise fallback to IP
        return req.session?.id || req.ip;
    }
});
app.use('/api/', limiter);

// Security middleware
app.use(helmet({
    contentSecurityPolicy: {
        directives: {
            defaultSrc: ["'self'"],
            styleSrc: ["'self'", "'unsafe-inline'", "https://fonts.googleapis.com"],
            fontSrc: ["'self'", "https://fonts.gstatic.com"],
            scriptSrc: ["'self'", "'unsafe-inline'", "https://esm.run"],
            connectSrc: [
                "'self'",
                "https://api.groq.com",
                "https://neobranium.onrender.com"
            ]
        }
    }
}));

const allowedOrigins = [
    'https://neobranium.web.app',
    'http://localhost:5500',
    'http://localhost:5501',
    'http://127.0.0.1:5500',
    'http://127.0.0.1:5501',
    ...((process.env.ALLOWED_ORIGINS || '').split(',').map(o => o.trim()).filter(Boolean))
];

app.use(cors({
    origin: function (origin, callback) {
        // Allow requests with no origin (like mobile apps or curl requests if explicitly permitted later)
        if (!origin) return callback(null, true);

        const isAllowed = allowedOrigins.some(allowed => origin.startsWith(allowed));
        if (isAllowed) {
            return callback(null, true);
        }

        return callback(new Error('CORS Error: Origin not allowed'), false);
    },
    credentials: true // IMPORTANT: Needed to send cookies generated by express-session!
}));

// Strict server-side origin check middleware
const strictOriginCheck = (req, res, next) => {
    // Only apply strict checks to /api routes
    if (!req.path.startsWith('/api/')) return next();

    const origin = req.headers.origin || req.headers.referer;

    // Reject requests with absolutely no origin/referer
    if (!origin) {
        console.warn(`🚨 Blocked direct API call (No Origin): ${req.ip}`);
        return res.status(403).json({ reply: 'Forbidden: Direct API access is not allowed' });
    }

    const isAllowed = allowedOrigins.some(allowedOrigin => origin.startsWith(allowedOrigin));

    if (!isAllowed) {
        console.warn(`🚨 Blocked API call from unauthorized origin: ${origin} (IP: ${req.ip})`);
        return res.status(403).json({ reply: 'Forbidden: Invalid Origin' });
    }

    next();
};

app.use(strictOriginCheck);

app.use(express.json({ limit: '2mb' }));

// GROQ API INTEGRATION - Initialize Groq API key
const groqApiKey = process.env.GROQ_API_KEY;
if (!groqApiKey) {
    console.error('❌ Missing GROQ_API_KEY in environment');
    // Optionally process.exit(1) in non-dev environment,
    // but if you want server to start and fail per-request, keep going.
}

// GROQ API INTEGRATION - Define model constant
const GROQ_MODEL = process.env.GROQ_MODEL || 'llama-3.3-70b-versatile';

// In-memory fallback if Redis is down
const fallbackMemory = new Map();

// Helper to get memory (Redis preferred)
async function getUserMemory(userId) {
    if (redisClient.isReady) {
        try {
            const data = await redisClient.hGet('user_memory', userId);
            if (data) {
                const parsed = JSON.parse(data);
                // Convert stringified dates back to Date objects
                parsed.sessionStart = new Date(parsed.sessionStart);
                return parsed;
            }
        } catch (e) {
            console.error('Redis memory fetch failed:', e);
        }
    }
    // Fallback
    return fallbackMemory.get(userId);
}

// Helper to save memory (Redis preferred)
async function saveUserMemory(userId, memoryData) {
    if (redisClient.isReady) {
        try {
            // Redis hashes take strings, so JSON.stringify the object
            // Use 'topics' as an Array because Set doesn't stringify well
            await redisClient.hSet('user_memory', userId, JSON.stringify(memoryData));
            // Expire memory after 1 hour of inactivity
            await redisClient.expire('user_memory', 3600);
            return;
        } catch (e) {
            console.error('Redis memory save failed:', e);
        }
    }

    // Fallback: use Map
    fallbackMemory.set(userId, memoryData);

    // Cleanup fallback Map periodically
    const now = Date.now();
    const maxAge = 60 * 60 * 1000; // 1 hour
    for (const [id, mem] of fallbackMemory) {
        if (now - mem.sessionStart.getTime() > maxAge) {
            fallbackMemory.delete(id);
        }
    }
    if (fallbackMemory.size > 1000) {
        const entries = Array.from(fallbackMemory.entries()).sort((a, b) => a[1].sessionStart - b[1].sessionStart);
        const toRemove = entries.slice(0, entries.length - 500);
        toRemove.forEach(([id]) => fallbackMemory.delete(id));
    }
}

// Helper functions
const detectQueryType = (text) => {
    const patterns = {
        code: /write|code|programming|python|javascript|java|function|class|html|css/i,
        math: /math|algebra|calculus|geometry|equation|solve|calculate/i,
        science: /science|physics|chemistry|biology|experiment|lab|formula/i,
        study: /study|learn|tips|technique|remember|understand|explain/i
    };

    for (const [type, pattern] of Object.entries(patterns)) {
        if (pattern.test(text)) return type;
    }
    return 'general';
};

const formatResponse = (text, queryType) => {
    if (queryType === 'code' && !text.includes('```')) {
        return `\`\`\`\n${text}\n\`\`\``;
    }
    return text;
};

// Main chat endpoint
app.post('/api/chat', async (req, res) => {
    const isProd = process.env.NODE_ENV === 'production';
    
    // 🛡️ SECURITY FIX: Ignore any Authorization header sent by the client.
    // The server uses its own GROQ_API_KEY from environment variables.
    if (req.headers.authorization) {
        console.warn(`⚠️ Client sent Authorization header to /api/chat. Ignoring it. IP: ${req.ip}`);
    }

    try {
        const { message, history = [] } = req.body;

        // 🛡️ INPUT VALIDATION
        if (typeof message !== 'string' || !message.trim()) {
            return res.status(400).json({
                error: 'Bad Request',
                reply: 'Please provide a valid text message.'
            });
        }

        // Limit message length to 10k characters to prevent abuse
        if (message.length > 10000) {
            return res.status(400).json({
                error: 'Payload Too Large',
                reply: 'Message is too long. Please shorten your request.'
            });
        }

        if (!Array.isArray(history)) {
            return res.status(400).json({
                error: 'Bad Request',
                reply: 'Invalid conversation history format.'
            });
        }

        // Limit history to last 15 messages to stay within reasonable context
        const validatedHistory = history.slice(-15);

        console.log('📨 Incoming chat request:', {
            ip: req.ip,
            userAgent: req.get('User-Agent'),
            sessionId: req.session.id,
            ...(isProd ? { msgLength: message.length } : { body: { message, historyCount: validatedHistory.length } })
        });

        // 🔒 Secure Fix: Use the server-generated session ID instead of trusting the client
        const secureUserId = req.session.id || 'fallback';

        // Get or create user memory
        let memory = await getUserMemory(secureUserId);

        if (!memory) {
            memory = {
                name: null,
                topics: [], // Using Array instead of Set for Redis JSON combability
                preferences: {},
                sessionStart: new Date(),
                messageCount: 0
            };
        }

        memory.messageCount++;

        // Detect name if mentioned
        const nameMatch = message.match(/my name is (\w+)|i am (\w+)|call me (\w+)/i);
        if (nameMatch) {
            memory.name = nameMatch[1] || nameMatch[2] || nameMatch[3];
        }

        // Track topics
        const queryType = detectQueryType(message);
        if (!memory.topics.includes(queryType)) {
            memory.topics.push(queryType);
        }

        // Save updated memory asynchronously (don't block the request)
        saveUserMemory(secureUserId, memory).catch(err => console.error("Memory track error:", err));

        // Build system prompt
        const systemIdentity = `You are NS-x AI Learning Assistant from the NeoBranium platform. NeoBranium is a learning platform focused on science, mathematics, programming, quizzes, and study tools for students. NeoBranium was created by Shubham Singh, a student who enjoys science, mathematics, programming, and building educational tools for students. In all responses, act as a friendly private learning assistant and do not reveal private details (location, school, phone, email, personal life). If asked about who made you, who created you, who owns this AI, who is Shubham Singh, or what is NeoBranium, reply: "This AI assistant is part of the NeoBranium learning platform created by Shubham Singh. He is a student who enjoys science, mathematics, and programming and built this platform to help students learn more effectively."`;

        const queryContext = queryType === 'code'
            ? 'You are a programming expert. Provide code examples with explanations.'
            : queryType === 'math' || queryType === 'science'
                ? 'You are a STEM expert. Explain concepts clearly with examples.'
                : 'You are a helpful learning assistant.';

        const personalContext = memory.name
            ? `The user's name is ${memory.name}. `
            : '';

        const historyContext = history
            .slice(-5)
            .map(h => `${h.role}: ${h.content}`)
            .join('\n');

        // GROQ API INTEGRATION - Build messages array
        const systemContent = `${systemIdentity} ${queryContext}`;
        const userContent = `${personalContext}User question: ${message}\n\nRespond in a helpful, educational manner. Use markdown for formatting.\nIf explaining code, always provide examples.\nBe encouraging and patient with learners.`;
        const messages = [
            { role: 'system', content: systemContent },
            ...validatedHistory,
            { role: 'user', content: userContent }
        ];

        // Log request for debugging
        console.log('📤 Sending to Groq API:', {
            model: GROQ_MODEL,
            messagesCount: messages.length,
            messages: messages.map(m => ({ role: m.role, contentLength: m.content.length }))
        });

        // Prepare request body
        const requestBody = {
            model: GROQ_MODEL,
            messages: messages,
            temperature: 0.7,
            max_tokens: 4096
        };

        console.log("FINAL GROQ REQUEST:", JSON.stringify(requestBody, null, 2));

        // Check if API key is available
        if (!groqApiKey) {
            console.error('❌ Missing GROQ_API_KEY');
            return res.status(500).json({ reply: 'AI service unavailable' });
        }

        let groqResponse;
        try {
            groqResponse = await fetch('https://api.groq.com/openai/v1/chat/completions', {
                method: 'POST',
                headers: {
                    'Authorization': `Bearer ${groqApiKey}`,
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify(requestBody)
            });
        } catch (fetchError) {
            console.error('❌ Fetch error:', fetchError);
            return res.status(500).json({ reply: 'AI request failed' });
        }

        if (!groqResponse.ok) {
            const errorText = await groqResponse.text();
            console.error('❌ Groq API error:', groqResponse.status, errorText);
            return res.status(500).json({ reply: 'AI request failed' });
        }

        let groqData;
        try {
            groqData = await groqResponse.json();
        } catch (jsonError) {
            console.error('❌ Failed to parse Groq response:', jsonError);
            return res.status(500).json({ reply: 'AI request failed' });
        }

        if (!groqData.choices || groqData.choices.length === 0) {
            console.error('❌ Groq API returned no choices:', groqData);
            return res.status(500).json({ reply: 'AI request failed' });
        }

        let text = groqData.choices[0].message.content;
        if (!text) {
            console.error('❌ Groq API returned empty content');
            return res.status(500).json({ reply: 'AI request failed' });
        }

        // Format and return
        text = formatResponse(text, queryType);

        console.log('✅ Chat response sent:', { reply: text.substring(0, 100) + '...' });

        res.json({
            reply: text
        });

    } catch (error) {
        console.error('❌ Chat request failed:', error);
        res.status(500).json({
            reply: 'AI request failed'
        });
    }
});

// Health check endpoint
app.get('/api/health', (req, res) => {
    res.json({
        status: 'healthy',
        timestamp: new Date().toISOString(),
        environment: process.env.NODE_ENV,
        redis: redisClient.isReady ? 'connected' : 'disconnected'
    });
});

// Statistics endpoint
app.get('/api/stats', async (req, res) => {
    try {
        let activeUsers = 0;
        let totalMessages = 0;
        const topicMap = new Map();

        let allMemories = [];

        if (redisClient.isReady) {
            // Fetch from Redis
            const allRedisData = await redisClient.hGetAll('user_memory');
            allMemories = Object.values(allRedisData).map(val => JSON.parse(val));
        } else {
            // Fetch from fallback Map
            allMemories = Array.from(fallbackMemory.values());
        }

        activeUsers = allMemories.length;

        for (const memory of allMemories) {
            totalMessages += memory.messageCount || 0;
            const topics = memory.topics || [];
            for (const topic of topics) {
                topicMap.set(topic, (topicMap.get(topic) || 0) + 1);
            }
        }

        const stats = {
            activeUsers,
            totalMessages,
            topicDistribution: Object.fromEntries(topicMap)
        };

        res.json(stats);
    } catch (error) {
        console.error("Stats processing error:", error);
        res.status(500).json({ error: "Failed to load stats" });
    }
});

// Serve static files (HTML, CSS, JS, images, etc.)
app.use(express.static(path.join(__dirname)));

// Serve static files in production
if (process.env.NODE_ENV === 'production') {
    app.use(express.static(path.join(__dirname, '../')));

    app.get('*', (req, res) => {
        res.sendFile(path.join(__dirname, '../index.html'));
    });
}

// Error handling middleware
app.use((err, req, res, next) => {
    console.error('Server Error:', err);
    res.status(500).json({
        reply: 'Internal server error. Please try again later.'
    });
});

const PORT = process.env.PORT || 3000;

app.listen(PORT, () => {
    console.log(`🚀 Server running on port ${PORT}`);
    console.log(`📝 Environment: ${process.env.NODE_ENV || 'development'}`);
    console.log(`🔑 Groq Model: ${GROQ_MODEL}`);
});